- name: "Pre-requisites python3 library"
  pip:
     name:
       - pyaml==20.4.0
       - paramiko==2.7.2
     executable: pip3
  delegate_to: "client-1"
   
- name: "Generate and collect support bundle"
  command: python3 /root/PerfProBenchmark/sb_gen_collect.py
  delegate_to: "client-1"
