#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

set -e
set -x

SCRIPT_PATH="$(readlink -f $0)"
SCRIPT_DIR="${SCRIPT_PATH%/*}"

function main()
{
    local motr_trace_location=$($SCRIPT_DIR/find_motr_trace_location.sh)
    rm -rf $motr_trace_location/m0d-*/m0trace.* || true

    # delete all m0trace/addb files generated by Motr/s3server
    rm -rf /var/log/seagate/motr/* || true

    # delete all m0trace files generated by Motr
    rm -rf /var/motr/m0d-*/m0trace.* || true
}

main $@
exit $?