#!/usr/bin/env bash
#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-


RESULT_DB="./m0play.db"

function main()
{
    cp "$1" $RESULT_DB
    shift

    TABLES=$(echo '.tables' | sqlite3 $RESULT_DB)

    # TABLES="client_to_dix dix_to_mdix dix_to_cas cas_to_rpc"

    for db in $@; do
        echo "merge $db"
        merge_db $db
    done

}

function merge_db()
{
    local db_path=$1

    local sql="attach '$db_path' as db2;"
    for table in $TABLES; do
        sql="$sql BEGIN; insert into $table select ALL_FIELDS from db2.$table; COMMIT;"
    done
    sql="$sql detach db2;"

    echo $sql | sed 's/ALL_FIELDS/*/g' | sqlite3 $RESULT_DB
}

main $@
exit $?
