#!/usr/bin/env bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

SCRIPT_PATH="$(readlink -f $0)"
SCRIPT_DIR="${SCRIPT_PATH%/*}"


function main()
{
    local artif_host=$1
    local artifacts_dir=$2
    local app=$3 #motr, s3server, m0crate
    shift
    shift
    shift
    
    
    if [[ "$app" == "motr" ]]; then

        MOTR_TRACE_DIR=$($SCRIPT_DIR/find_motr_trace_location.sh)

        for ios_fid in $@; do
            local ios_dir="$MOTR_TRACE_DIR/m0d-$ios_fid"

            if [[ -e $ios_dir ]]; then
                pushd $ios_dir

                for filename in $(ls m0trace.*); do
                    echo "dump $filename"
                    m0trace -i ${filename} -o ${filename}.txt 2>/dev/null
                done

                scp m0trace*txt root@${artif_host}:${artifacts_dir}
                rm -rf m0trace*txt || true
                popd
            fi
        done
    elif [[ "$app" == "s3server" ]]; then
        
        for s3dir in $(ls /var/log/seagate/motr | grep s3server); do
            pushd /var/log/seagate/motr/$s3dir

            for filename in $(ls m0trace.*); do
                echo "dump $filename"
                m0trace -i ${filename} -o ${filename}.txt 2>/dev/null
            done

            scp m0trace*txt root@${artif_host}:${artifacts_dir}/$(hostname)/$s3dir
            rm -rf m0trace*txt || true
            popd
        done
    elif [[ "$app" == "m0crate" ]]; then
        
        local m0crate_workdir="$1"
        shift

        if [[ -e "$m0crate_workdir" ]]; then
            pushd $m0crate_workdir

            for filename in $(ls m0trace.*); do
                m0trace -i ${filename} -o ${filename}.txt 2>/dev/null
            done

            scp m0trace*txt root@${artif_host}:${artifacts_dir}
            rm -rf m0trace*txt || true
            popd
        fi
    else
        echo "unsupported app: $app"
    fi
}

main $@
exit $?
