---
# For host file update : add for more nodes/clients in environment or remove if less nodes/clients .
NODES:  
  - 1:  # node_number_srvnode-1: hostname of node1 .
  - 2:  # node_number_srvnode-2: hostname of node2 .
  - 3:  # node_number_srvnode-3: hostname of node3 .
CLIENTS: 
  - 1:  #client_number: hostname of client  
  - 2:  #client_number: hostname of client  

# For Build and SystemUnderTest INFO
BUILD_INFO:  # Please select the menthod to collect Build info from given options : RELEASE.INFO / USER_INPUT / FROM_K8
BUILD_URL: # insert here is RELEASE.INFO is selected.
# Please insert below details if USER_INPUT is selected.
DOCKER_INFO:  # add the docker info which is used for perf runs Eg: 'ghcr.io/seagate/cortx-all:2.0.0-770'
BUILD: 
VERSION: 
BRANCH: 
OS: 
CLUSTER_PASS:  # Please enter the cluser password.
SOLUTION: lc    # DB collection for uploading data legacy, lc or lr
EXECUTION_TYPE: normal # execution type can be 'normal' or 'sanity'

# For PerfPro MongoDB related Entries
END_POINTS: 
SYSTEM_STATS: True # If True, enter cluster nodes for installing pkgs, collecting sysstats and uploading sysstats. If Flase, won't enter cluster nodes
PC_FULL: 0 # Select for system percentage full before test. 
OVERWRITE: False # select True or False to overwrite the DB entries for same Primary Key
CUSTOM: NA # Default is NA. Update with single string for special config eg: CorvStd, CorvHiPerf, 5u84Std, 5u84HiPerf, SSD, DIEnabled, PODsetup etc
DEGRADED_IO: False   # Select True/False to test Degraded read feature
COPY_OBJECT: False   #Select True/False to test Copy object feature

#Enter Below details for log collection on NFS repo
NFS_SERVER: 
NFS_EXPORT: 
NFS_MOUNT_POINT: 
NFS_FOLDER: 

#END
required_vars:
  - NODES
  - CLIENTS
  - BUILD_URL
  - CLUSTER_PASS
  - END_POINTS
  - PC_FULL
  - OVERWRITE
  - CUSTOM
  - DEGRADED_READ
  - NFS_SERVER
  - NFS_EXPORT
  - NFS_MOUNT_POINT
  - NFS_FOLDER
