---
Degraded_read_load:
   sessions:
      - 1
      - 3
      - 300
      - 600
      - 900
      - 1200
      - 1500
      - 1800

   objs:
      - { objsize: '256Kb', numsamples: '10000'}
      - { objsize: '16Mb', numsamples: '10000'}

buckets:
   - 1
