---
# vars file for benchmark
db_server:  # Enter the DB server's FQDN or IP details.
db_port:  # Enter the Port number as per MongoDB config.
db_name:  # Enter the DB name as configured on DB server
db_user:  # Enter the DB User's credentials.
db_passwd:  # Enter DB user's password.
db_database:  # Enter the Database details . 

# Following are the default collections details, These can be modified as per User's specific configuration. 
SANITY:
  sanity_details_collection: sanity_run_details # stores sanity repo and user-specific details
  sanity_config_collection: sanity_config # stores run specific configurations
  sanity_dbcollection: sanity_results # stores performance metrics and record-specific data
R1:
  db_collection: results_1
  sysstat_collection: systemresults_1
  config_collection: configurations_1
R2:
  db_collection: results_2
  sysstat_collection: systemresults_2
  config_collection: configurations_2
LC:
  db_collection: lc
  sysstat_collection: lc_sys
  config_collection: lc_config
LR:
  db_collection: lr
  sysstat_collection: lr_sys
  config_collection: lr_config
db_url:  # Enter the DB server URL which can be accessed. 

