---
# For host file update : add for more nodes/clients in environment or remove if less nodes/clients .
NODES:  
  - 1:  # node_number_srvnode-1: hostname of node1 .
  - 2:  # node_number_srvnode-2: hostname of node2 .
  - 3:  # node_number_srvnode-3: hostname of node3 .
CLIENTS: 
  - 1:  #client_number: hostname of client  
  - 2: 

# For Build and SystemUnderTest INFO
BUILD_URL: http://cortx-storage.colo.seagate.com/releases/cortx/github/stable/centos-7.8.2003/140/
CLUSTER_PASS: seagate1
CHANGE_PASS: 'no'
PRVSNR_CLI_REPO: https://github.com/Seagate/cortx-prvsnr@cortx-1.0#subdirectory=api/python
PREREQ_URL: https://raw.githubusercontent.com/Seagate/cortx-prvsnr/cortx-1.0/cli/src/cortx-prereqs.sh

# If you want to change server password then enter below details
SERVICE_USER:
SERVICE_PASS:

# For DB related Entries
PC_FULL: 0 # Select between 30% or 75% for system percentage full 
OVERWRITE: False # select True or False to overwrite the DB entries for same Primary Key

#Enter Below details for log collection on NFS repo
NFS_SERVER: 
NFS_EXPORT: 
NFS_MOUNT_POINT: 
NFS_FOLDER: 
#End of NFS config

#END
required_vars:
  - REIMAGE
  - NODES
  - CLIENTS
  - BUILD_URL
  - CLUSTER_PASS
  - SATELLITE_UN
  - SATELLITE_PW
  - CHANGE_PASS
  - PC_FULL
  - OVERWRITE
  - NFS_SERVER
  - NFS_EXPORT
  - NFS_MOUNT_POINT
  - NFS_FOLDER

