---
# reimage as 'yes' or 'no'
REIMAGE: 
NODES:
  -  #hostname of node1
  -  #hostname of node2
  -  #hostname of node3  so on till Nth node.
CLIENTS: 
  -  #list of the clients. 
BUILD_URL: 
OS_TYPE:      # Cluster OS type either CENTOS and RHEL
CLUSTER_PASS: seagate1
CHANGE_PASS: 'no'
PRVSNR_CLI_REPO: https://github.com/Seagate/cortx-prvsnr@cortx-1.0#subdirectory=api/python
PREREQ_URL: https://raw.githubusercontent.com/Seagate/cortx-prvsnr/cortx-1.0/cli/src/cortx-prereqs.sh

# If you want to change server password then enter below details
SERVICE_USER:
SERVICE_PASS:

#Enter Below details for log collection on NFS repo
NFS_SERVER: 
NFS_EXPORT: 
NFS_MOUNT_POINT: 
NFS_FOLDER: 
#End of NFS config

#END
required_vars:
  - REIMAGE
  - NODES
  - CLIENTS
  - BUILD_URL
  - CLUSTER_PASS
  - SATELLITE_UN
  - SATELLITE_PW
  - CHANGE_PASS
  - NFS_SERVER
  - NFS_EXPORT
  - NFS_MOUNT_POINT
  - NFS_FOLDER

