#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-
#

common:
  version: 1
  description: Test Motr corruption test on cluster
  priority: 11
  batch_id: null
  user: username@seagate.com
  send_email: true
  type: m0corrupt
  timeout: 15m
  nodes:
    - srv: smc33-m09.colo.seagate.com
      cli: smc33-m09.colo.seagate.com
    - srv: smc34-m09.colo.seagate.com
      cli: smc34-m09.colo.seagate.com

workload:
  - app: m0crate
    param:
      cli_options: "LAYOUT_ID=9 IOSIZE=32m BLOCK_SIZE=32m NR_THREADS=8 NR_OBJS=8"
  - app: m0crate
    param:
      cli_options: "LAYOUT_ID=9 IOSIZE=256m BLOCK_SIZE=32m NR_THREADS=8 NR_OBJS=8"

ha: hare

motr:
  git: 1aa25676d62d56d92712bd637afa188b92d3adb7
  build_options: "--disable-altogether-mode --enable-release --with-trace-ubuf-size=64"
  config_overrides: null

execution_options:
  no_motr_trace: true
  no_m0trace_files: true
  no_m0trace_dumps: true
  no_addb_stobs: true
  no_addb_dumps: true
  no_m0play_db: true
