#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-
#

common:
  version: 1
  description: Short text description
  priority: 2
  batch_id: m0crate test
  type: m0crate
  user: maxim.malezhin@seagate.com
  send_email: false
  nodes:
    - srv: 
      cli: 
    - srv: 
      cli: 

pre_exec_cmds:
 - cmd: "/bin/echo"
   parameters: "Hello Motr!"
 - cmd: "sleep"
   parameters: "15"

post_exec_cmds:
 - cmd: "/bin/echo"
   parameters: "Goodbye Motr..."
 - cmd: "sleep"
   parameters: "15"

workload:
  - app: m0crate
    param:
      config_overrides:
        LAYOUT_ID: 9
        IOSIZE: 1g
        BLOCK_SIZE: 112m
        NR_THREADS: 2
        NR_OBJS: 1
  - app: sleep
    param:
      cli_options: "60"
  - app: m0crate
    param:
      config_overrides:
        LAYOUT_ID: 9
        IOSIZE: 1g
        BLOCK_SIZE: 112m
        NR_THREADS: 2
        NR_OBJS: 1

ha: halon

motr:
  git: dev
  #git: 3c6e1148ff5fb18b81236700396bd7881ad61c18
  build_options: "--disable-altogether-mode --enable-release --with-trace-ubuf-size=64"
  config_overrides: null

execution_options:
  no_motr_trace: false
  no_m0trace_files: false
  no_m0trace_dumps: false
  no_addb_stobs: false
  no_addb_dumps: false
  no_m0play_db: false
