#!/usr/bin/env bash
#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-

set -x
set -e

SCRIPT_PATH="$(readlink -f $0)"
SCRIPT_DIR="${SCRIPT_PATH%/*}"

. ${SCRIPT_DIR}/../common/common_funcs

S3_CRED_FILE="${SCRIPT_DIR}/s3_credentials_$(hostname -s)"
LDAP_USER="sgiamadmin"
LDAP_PASS="ldapadmin"

function check_and_create_s3_cred() {
    if [[ ! -f "$S3_CRED_FILE" ]]; then
        _info "creation s3 credentials in $S3_CRED_FILE"

        local rnd_str=`dd if=/dev/urandom bs=1024 count=1 2>/dev/null \
            | tr -dc a-z | head -c10`
        local hostname=$(hostname -s)
        local username="perf_${hostname}_${rnd_str}"

        $SCRIPT_DIR/s3_create_user --name $username \
            --email ${username}@seagate.com --ldap-user $LDAP_USER \
            --ldap-pass $LDAP_PASS > $S3_CRED_FILE
    fi
}

if [[ -z "$S3_CRED_FILE" ]]; then
    _err "path to credentials file hasn't been specified"
    exit 1
fi

check_and_create_s3_cred
