#!/usr/bin/env bash
#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-


. "${SCRIPT_DIR}"/../common/common_funcs

function parse_s3_cred_file() {
    local s3_cred_file=$1

    if [[ -z "$s3_cred_file" ]]; then
        _err "path to credentials file is not specified"
        exit 1
    fi

    S3_CRED_ACCESS_KEY=$(cat "$s3_cred_file" | grep AccessKeyId \
        | awk -F '=' '{print $2}')

    S3_CRED_SECRET_KEY=$(cat "$s3_cred_file" | grep SecretKey \
        | awk -F '=' '{print $2}')

    if [[ -z "$S3_CRED_ACCESS_KEY" || -z "$S3_CRED_SECRET_KEY" ]]; then
        _err "invalid format of S3 credentials file $s3_cred_file"
        exit 1
    fi
}

function parse_s3_nodes_map() {
    local nodes_map=$@

    if [[ -z "$nodes_map" ]]; then
        _err "nodes mapping is not specified"
        exit 1
    fi

    CLI_NODES=""
    for mapping in $nodes_map; do
        local cli=$(echo "$mapping" | grep $(hostname) | awk -F '=' '{print $2}')
        if [[ -z $CLI_NODES ]]; then
            CLI_NODES="$cli"
        else
            CLI_NODES="$CLI_NODES,$cli"
        fi
    done
    # Don't return an error if CLI_NODES is empty - this is valid situation
}
