#!/usr/bin/env python3
#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-


import sys

S3SERVER_ENTRY_FORMAT = "    server s3-instance-{1} 0.0.0.0:{0} check    # s3 instance {1}"

def find_s3server_lines(file_path):
    line_numbers = list()

    with open(file_path) as f:
        ln = 0
        is_backend_section = False
        for line in f:
            ln += 1
            stripped_line = line.lstrip()

            #ignore empty lines and comments
            if len(stripped_line) == 0 or stripped_line.startswith("#"):
                continue

            if not line.startswith(" "):
                #next section is found
                if line.startswith("backend app-main"):
                    is_backend_section = True
                else:
                    is_backend_section = False

            if is_backend_section:
                if stripped_line.startswith("server"):
                    line_numbers.append(ln)
    return line_numbers

def patch_file(file_path, lines_for_delete, instance_nr, port_start):
    with open(file_path) as f2:
        ln = 0
        for line in f2:
            ln += 1

            if ln not in lines_for_delete:
                print(line, end="")
            elif ln == lines_for_delete[0]:
                for instance in range(instance_nr):
                    print(S3SERVER_ENTRY_FORMAT.format(port_start, instance + 1))
                    port_start += 1

def main():
    file_path = sys.argv[1]
    instance_nr = int(sys.argv[2])
    port_start = int(sys.argv[3])

    line_numbers = find_s3server_lines(file_path)
    patch_file(file_path, line_numbers, instance_nr, port_start)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e, file=sys.stderr)
        exit(1)
    exit(0)
