#!/usr/bin/env bash
#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-

set -x
set -e

SCRIPT_PATH="$(readlink -f $0)"
SCRIPT_DIR="${SCRIPT_PATH%/*}"

. ${SCRIPT_DIR}/../common/common_funcs
. ${SCRIPT_DIR}/functions

S3_SRV_CLI_MAP=$1

function create_bucket() {
    local aws_bin="/usr/local/bin/aws"
    local bucket="seagatebucket-$(hostname -s)"
    $EX_CLI "$aws_bin s3 ls s3://$bucket &> /dev/null || $aws_bin s3 mb s3://$bucket"
}

if [[ -z "$S3_SRV_CLI_MAP" ]]; then
        _err "servers-clients map wasn't specified"
        exit 1
fi

parse_s3_nodes_map $S3_SRV_CLI_MAP

if [ -z $CLI_NODES ]; then
    exit 0
fi

EX_CLI="pdsh -S -w $CLI_NODES"

create_bucket
