---
CLIENT: iu09-r21.pun.seagate.com
NODE1: sm20-r22.pun.seagate.com
NODE2: sm21-r22.pun.seagate.com
USER: root
CLUSTER_PASS: seagate1
CLUSTER_IP: 172.19.222.20 
MGMT_VIP: 10.237.65.62
PUB_NIC: enp175s0f0
PRIVATE_NIC: enp175s0f1
DATA_IP_NODE1: 172.19.22.20
DATA_IP_NODE2: 172.19.22.21
CONTROLLER_A_IP: 10.237.65.202
CONTROLLER_B_IP: 10.237.66.1
CONTROLLER_USER: manage
CONTROLLER_PASS: 'Seagate123$'
BMC_USER: ADMIN
BMC_PASS: ADMIN
BUILD_URL: http://cortx-storage.colo.seagate.com/releases/eos/Cortx-1.0.0-35-rc14/
PREREQ_URL: http://gitlab.mero.colo.seagate.com/eos/provisioner/ees-prvsnr/raw/Cortx-v1.0.0_Beta/cli/src/cortx-prereqs.sh
AUDO_DEPLOY_URL: http://gitlab.mero.colo.seagate.com/eos/provisioner/ees-prvsnr/raw/Cortx-v1.0.0_Beta/cli/src/auto-deploy-eos
