---
 - name: "Create List of nodes to be added into Cluster"
   set_fact: nodelist={%for host in groups['nodes']%}{{hostvars[host]['ansible_host']}}{% if not loop.last %},{% endif %}{% endfor %}

 - name: "Importing configuration"
   include_vars: degraded_read_config.yml

 - name: "[HSBench] Preparing Configuration for Degraded read"
   vars:
      runconfig:
         nodelist: "{{ nodelist }}"
         numclients: "{{ item[0] }}"
         objsize: "{{ item[1].objsize }}"
         numsamples: "{{ item[1].numsamples }}"
         buckets: "{{ buckets[0] }}"
         hsb_var: "{{ hsb_var }}"
         cluster_state: "{{ cluster_state }}"
   ansible.builtin.include_tasks: execute_dr_hsbench.yml
   loop: "{{ Degraded_read_load.sessions|product(Degraded_read_load.objs)|list }}"









