---
 - name: "Preaparing Cluster Node List"
   set_fact: nodelist={%for host in groups['nodes']%}{{hostvars[host]['ansible_host']}}{% if not loop.last %},{% endif %}{% endfor %}

 - name: "Importing configuration"
   include_vars: degraded_read_config.yml

 - name: "[S3Bench] Preparing Configuration for Degraded read"
   vars:
      runconfig:
         nodelist: "{{ nodelist }}"
         numclients: "{{ item[0] }}"
         objsize: "{{ item[1].objsize }}"
         numsamples: "{{ item[1].numsamples }}"
         s3_var: "{{ s3_var }}"
         cluster_state: "{{ cluster_state }}"
   ansible.builtin.include_tasks: execute_dr_s3bench.yml
   loop: "{{ Degraded_read_load.sessions|product(Degraded_read_load.objs)|list }}"

