---
 - name: "[S3bench] Starting systemstats collection {{ runconfig.objsize }}-{{ runconfig.numclients }}sessions"
   delegate_to: "clientnode-1"
   shell: pdsh -S -w {{runconfig.nodelist}} "python3 '/root/PerfProBenchmark/system_monitoring/systemMonitoring.py' '/root/PerfProBenchmark/main.yml' '/root/PerfProBenchmark/config.yml' {{ runconfig.objsize }} 'S3bench'" &

 - name: "[S3bench] Starting execution {{ runconfig.objsize }}-{{ runconfig.numclients }}sessions"
   delegate_to: "{{ client }}"
   shell: |
      cd /root/PerfProBenchmark/s3bench/
      ./run_s3benchmark.sh -nc {{ runconfig.numclients }} -ns {{ runconfig.numsamples }} -s {{ runconfig.objsize }}
   async: 86400
   poll: 0
   loop: "{{ groups['clients'] }}"
   loop_control:
      loop_var: "client"
   register: async_results

 - name: "[S3bench] Running {{ runconfig.objsize }}-{{ runconfig.numclients }}sessions"
   async_status:
      jid: "{{ async_result_item.ansible_job_id }}"
   delegate_to: "{{ async_result_item.client }}"
   loop: "{{ async_results.results }}"
   loop_control:
      loop_var: "async_result_item"
   register: async_poll_results
   until: async_poll_results.finished
   retries: 8640
   delay: 10

 - name: "[S3bench] Stopping systemstats collection {{ runconfig.objsize }}-{{ runconfig.numclients }}sessions"
   delegate_to: "clientnode-1"
   shell: pdsh -S -w {{runconfig.nodelist}} "python3 /root/PerfProBenchmark/system_monitoring/stopSystemMonitoring.py"
