# Seagate-tools: PerfPro
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-

---
 - name: "[S3Bench] Starting systemstats collection {{ runconfig.objsize }} - {{ runconfig.numclients }}session"
   delegate_to: "clientnode-1"
   shell: pdsh -S -w {{runconfig.nodelist}} "python3 '/root/PerfProBenchmark/system_monitoring/systemMonitoring.py' '/root/PerfProBenchmark/main.yml' '/root/PerfProBenchmark/config.yml' {{ runconfig.objsize }} 'S3bench'" &

 - name: "[S3Bench] Starting execution {{ runconfig.objsize }}-{{ runconfig.numclients }}session"
   delegate_to: "{{ client }}"
   shell: |
      cd /root/PerfProBenchmark/copy_object/
      ./copyobject_s3benchmark.sh -nc {{ runconfig.numclients }} -ns {{ runconfig.numsamples }} -s {{ runconfig.objsize }}
   async: 86400
   poll: 0
   loop: "{{ groups['clients'] }}"
   loop_control:
      loop_var: "client"
   register: async_results

 - name: "[S3Bench] Running {{ runconfig.objsize }} - {{ runconfig.numclients }}session"
   async_status:
      jid: "{{ async_result_item.ansible_job_id }}"
   delegate_to: "{{ async_result_item.client }}"
   loop: "{{ async_results.results }}"
   loop_control:
      loop_var: "async_result_item"
   register: async_poll_results
   until: async_poll_results.finished
   retries: 8640
   delay: 10

 - name: "[S3Bench] Stopping systemstats collection {{ runconfig.objsize }} - {{ runconfig.numclients }}session"
   delegate_to: "clientnode-1"
   shell: pdsh -S -w {{runconfig.nodelist}} "python3 /root/PerfProBenchmark/system_monitoring/stopSystemMonitoring.py"
