# Seagate-tools: PerfPro
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-

---
# #######################
# Following Tasks will be executed.
# # 1. 'hosts' file will be created from the template files.
# # 2. Host entry for all the S3 Server nodes will be added to the 'hosts' file
# # 3. Host entry for all the S3 client nodes will be added to the 'hosts' file
# #######################

 - name : create hosts file from hosts_template.bak
   copy:
    src: files/hosts_template
    dest: "{{ playbook_dir }}/inventories/hosts"

 - name: create server hosts entry
   lineinfile:
    path: "{{ playbook_dir }}/inventories/hosts"
    insertafter: '\[nodes\]'
    line:
     "srvnode-{{ item.key }} ansible_host={{ item.value }} "
   with_dict: "{{ NODES }}"

 - name: create clients hosts entry
   lineinfile:
    path: "{{ playbook_dir }}/inventories/hosts"
    insertafter: '\[clients\]'
    line:
     "clientnode-{{ item.key }} ansible_host={{ item.value }} "
   with_dict: "{{ CLIENTS }}"
