---
 - name: "[Orchestrator(localhost)] : Required packages"
   yum:
      name: expect
      state: present

 - name: "[Orchestrator(localhost)] : Generate SSH key pair if not already exist"
   openssh_keypair:
      path: "~/.ssh/id_rsa"
      type: rsa
      size: 4096
      state: present
      force: no
 
 - name: "[Orchestrator(localhost)] : Enabling Passwordless SSH to all hosts"
   script: files/passwordless_ssh.sh {{ hostvars[item]['ansible_user'] }} {{ hostvars[item]['ansible_host'] }} {{ CLUSTER_PASS }}
   ignore_errors: true
   with_items: "{{ groups['all'] }}"

 - name: "[All Hosts] : Required packages on all servers"
   yum:
      name: expect
      state: present
   delegate_to: "{{ item }}"
   with_items: "{{ groups['all'] }}"

 - name: "[All Clients] : Generate SSH key pair if not already exist"
   openssh_keypair:
      path: "~/.ssh/id_rsa"
      type: rsa
      size: 4096
      state: present
      force: no
   delegate_to: "{{ item }}"
   with_items: "{{ groups['clients'] }}"

 - name: "[All Clients] : Enabling Passwordless SSH to all hosts"
   script: files/passwordless_ssh.sh {{ hostvars[item[1]]['ansible_user'] }} {{ hostvars[item[1]]['ansible_host'] }} {{ CLUSTER_PASS }}
   ignore_errors: true
   delegate_to: "{{ item[0] }}"
   loop: "{{ groups.clients|product(groups.all)|list }}"
