# Seagate-tools: PerfPro
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-

---
 - name: "Installing required yum packages on clients"
   yum:
     name:
       - expect
       - ntp
       - python3
       - python3-pip
       - pdsh
       - go >= 1.15
       - java
       - curl
       - unzip
       - nc
     state: present
   delegate_to: "{{ item }}"
   with_items: "{{ groups['clients'] }}"

 - name: "Installing required yum packages on nodes"
   yum:
     name:
       - expect
       - ntp
       - sysstat
       - python3
       - python3-pip
     state: present
   delegate_to: "{{ item }}"
   with_items: "{{ groups['nodes'] }}"
   when: SYSTEM_STATS

 - name: "Updating python3 pip version on clients"
   shell: pip3 install update pip
   delegate_to: "{{ item }}"
   with_items: "{{ groups['clients'] }}"

 - name: "Updating required python3 packages on clients"
   pip:
     name:
       - setuptools_rust
       - wheel
       - PyYAML==5.3.1
       - requests==2.24.0
       - jsonschema==3.2.0
       - pymongo==3.11.0
       - pandas==1.0.5
       - datetime==4.3
       - yq
       - tabulate==0.8.10
     executable: pip3
     extra_args: --ignore-installed
   delegate_to: "{{ item }}"
   with_items: "{{ groups['clients'] }}"

 - name: "Updating required python3 packages on nodes"
   pip:
     name:
       - PyYAML==5.3.1
       - requests==2.24.0
       - jsonschema==3.2.0
       - pymongo==3.11.0
       - pandas==1.0.5
       - datetime==4.3
       - yq
     executable: pip3
     extra_args: --ignore-installed
   delegate_to: "{{ item }}"
   with_items: "{{ groups['nodes'] }}"
   when: SYSTEM_STATS

 - name: "[Services/daemons:start|stop|restart]: Checking network time protocol service daemon on clients"
   shell: systemctl stop ntpd ; /usr/sbin/ntpdate time.seagate.com ; systemctl start ntpd
   delegate_to: "{{ item }}"
   with_items: "{{ groups['clients'] }}"

 - name: "[Services/daemons:start|stop|restart]: Checking network time protocol service daemon on nodes"
   shell: systemctl stop ntpd ; /usr/sbin/ntpdate time.seagate.com ; systemctl start ntpd
   delegate_to: "{{ item }}"
   with_items: "{{ groups['nodes'] }}"
   when: SYSTEM_STATS

