# Seagate-tools: PerfPro
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-

---
 - name: Check for any  installed docker
   shell: rpm -qa |grep docker ; echo $?
   register: di

 - name: Install latest docker
   shell: |
     yum install yum-utils -y
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install docker-ce --nogpgcheck -y
   delegate_to: "clientnode-1"
   when: di.stdout == "1"

 - name : Start docker services and pull docker image
   shell: |
    systemctl start docker
    docker pull {{ DOCKER_INFO }}
   delegate_to: "clientnode-1"

 - name: Collect informartions from RELEASE.INFO
   shell: docker run {{ DOCKER_INFO }} cat /opt/seagate/cortx/RELEASE.INFO > /root/PerfProBenchmark/RELEASE.INFO
   delegate_to: "clientnode-1"

 - name: Copy RELEASE.INFO to Nodes.
   command: scp -r /root/PerfProBenchmark/RELEASE.INFO  {{ hostvars[item]['ansible_host'] }}:/root/PerfProBenchmark/RELEASE.INFO 
   delegate_to: "clientnode-1"
   loop: "{{ groups['nodes'] }}"
   when: SYSTEM_STATS

 - name: Copy RELEASE.INFO to remaining clients.
   command: scp -r /root/PerfProBenchmark/RELEASE.INFO  {{ hostvars[item]['ansible_host'] }}:/root/PerfProBenchmark/RELEASE.INFO
   delegate_to: "clientnode-1"
   loop: "{{ groups['clients'] }}"
   when: item != "clientnode-1"

 - name: Remove docker image
   shell: docker image rm {{ DOCKER_INFO }} --force
   delegate_to: "clientnode-1"

