common:
  version: 1
  description: s3bench benchmark
  priority: 1
  batch_id: null
  user: user@seagate.com
  send_email: false


common:
  version: 1
  description: Perf benchmark example
  priority: 1
  batch_id: null
  user: user@seagate.com
  send_email: false


#custom_build:
#  motr_repo_path:
#  hare_repo_path:
#  s3server_repo_path:
#  hare_commit_id:
#  motr_commit_id:
#  s3server_commit_id:


stats_collection:
  iostat: true
  dstat: true
  blktrace: true
  glances: false


benchmarks:
  - s3bench:
      BucketName: testbucket
      NumClients: 16
      NumSample: 32
      ObjSize: 16Mb
      EndPoint: https://s3.seagate.com


execution_options:
  mkfs: false
  m0trace: false
  addb: false
