---
# vars file for perfline_setup

# Specify POSTFIX value to customize the location of PerfLine (artifacts directory,
# log file location) or to be able install more than one version of PerfLine
# on the same cluster.
# Example:
# POSTFIX: '-dev'

POSTFIX: ''

S3BENCH_COMMIT_ID: 0126b7f
PERFLINE_DIR: /root/perfline{{ POSTFIX }}
ARTIFACTS_DIR: '/var/perfline{{ POSTFIX }}'
PERFLINE_LOGFILE: '/var/log/perfline{{ POSTFIX }}.log'
PERFLINE_SERVICE_NAME: 'perfline{{ POSTFIX }}'
PERFLINE_UI_SERVICE_NAME: 'perfline-ui{{ POSTFIX }}'
