runfiles:
    hs:     # path for hsbench run file
    cos:    # path for cosbench run file
    s3:     # path for s3bench run file

logger:
    hs:     # path for hsbench run log file
    cos:    # path for cosbench run log file
    s3:     # path for s3bench run log file

# shoulb be in MB
cos_object_size:    # object size for the cosbench run
