database:
    host: "ssc-vm-3541.colo.seagate.com"
    port: 8086
    database: "perfbot"

logfiles:
    hs: './Data/hsbench/hsbench.log'
    cos: './Data/cosbench/s3-5050rw.csv'
    s3: './Data/s3bench/s3bench_Numclients_1_NS_20_size_128Mb.log'
