---
 - name : "Doing cleanup before starting Degraded Read"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'cx'"
     cluster_state: "'normal-cleanup'"

 - name: "Running S3bench in write only mode"
   include: dr_s3bench.yml
   vars: 
     s3_var: "'-skipRead -skipCleanup'"
     cluster_state: "'normal-write'"

 - name: "Running HSbench in write only mode"
   include: dr_hsbench.yml
   vars: 
     hsb_var: "'ip'"
     cluster_state: "'normal-write'"

#Collecting read stats before failure

 - name: "Running read only S3bench in normal state of cluster"
   include: dr_s3bench.yml
   vars:
     s3_var: "'-skipWrite -skipCleanup'"
     cluster_state: "'normal-read'"

 - name: "Running read only HSbench in normal state of cluster"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'lg'"
     cluster_state: "'normal-read'"


#Fail the node 
## Yet to be implemented


#collect read stats

 - name: "Running read only S3bench in degraded state of cluster"
   include: dr_s3bench.yml
   vars:
     s3_var: "'-skipWrite -skipCleanup'"
     cluster_state: "'degraded-read'"

 - name: "Running read only HSbench in degraded state of cluster"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'lg'"
     cluster_state: "'degraded-read'"

#Boot the failed node
## Yet to be implemented


#Collect read starts after cluster is recovered and cleanup

 - name: "Running read only S3bench in recovered state of cluster"
   include: dr_s3bench.yml
   vars:
     s3_var: "'-skipWrite'"
     cluster_state: "'recovered-read'"

 - name: "Running read only HSbench in recovered state of cluster"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'lg'"
     cluster_state: "'recovered-read'"

 - name: "Cleaning up buckets and objects of HSbench"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'dcx'"
     cluster_state: "'recovered-cleanup'"

