---
 - name : "Doing cleanup before starting Degraded Read"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'cx'"

 - name: "Running S3bench in write only mode"
   include: dr_s3bench.yml
   vars: 
     s3_var: "'-skipRead -skipCleanup'"

 - name: "Running HSbench in write only mode"
   include: dr_hsbench.yml
   vars: 
     hsb_var: "'ip'"

#Collecting read stats before failure

 - name: "Running read only S3bench in normal state of cluster"
   include: dr_s3bench.yml
   vars:
     s3_var: "'-skipWrite -skipCleanup'"

 - name: "Running read only HSbench in normal state of cluster"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'lg'"


#Fail the node 
## Yet to be implemented


#collect read stats

 - name: "Running read only S3bench in degraded state of cluster"
   include: dr_s3bench.yml
   vars:
     s3_var: "'-skipWrite -skipCleanup'"

 - name: "Running read only HSbench in degraded state of cluster"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'lg'"

#Boot the failed node
## Yet to be implemented


#Collect read starts after cluster is recovered and cleanup

 - name: "Running read only S3bench in recovered state of cluster"
   include: dr_s3bench.yml
   vars:
     s3_var: "'-skipWrite'"

 - name: "Running read only HSbench in recovered state of cluster"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'lg'"

 - name: "Cleaning up buckets and objects of HSbench"
   include: dr_hsbench.yml
   vars:
     hsb_var: "'dcx'"


