---
# #######################
# Following Tasks will be executed.
# # 1. 'hosts' file will be created from the template files.
# # 2. Host entry for all the S3 Server nodes will be added to the 'hosts' file
# # 3. Host entry for all the S3 client nodes will be added to the 'hosts' file
# #######################

 - name : create hosts file from hosts_template.bak
   copy:
    src: files/hosts_template
    dest: "{{ playbook_dir }}/inventories/perfpro_deployment/hosts"

 - name: create server hosts entry
   lineinfile:
    path: "{{ playbook_dir }}/inventories/perfpro_deployment/hosts"
    insertafter: '\[nodes\]'
    line:
     "srvnode-{{ item.key }} ansible_host={{ item.value }} "
   with_dict: "{{ NODES }}"

 - name: create clients hosts entry
   lineinfile:
    path: "{{ playbook_dir }}/inventories/perfpro_deployment/hosts"
    insertafter: '\[clients\]'
    line:
     "clientnode-{{ item.key }} ansible_host={{ item.value }} "
   with_dict: "{{ CLIENTS }}"
