---

 - name: Pre-requisites packages for regression test cases
   yum:
     name:
       - sysstat
       - python3
       - python3-pip
     state: present
   delegate_to: "{{ item }}"
   with_items: "{{ groups['allserver'] }}"

 - name: Installation of golang on client server
   yum:
     name: go
     state: present
   delegate_to: "{{ groups['clientserver'][0] }}"
 
 - name: Pre-requisites python3 library
   pip:
     name: 
       - PyYAML==5.3.1
       - requests==2.24.0
       - jsonschema==3.2.0
       - pymongo==3.11.0
     executable: pip3
   delegate_to: "{{ item }}"
   with_items: "{{ groups['allserver'] }}"

 - name: Copying PerfProBenchmark tar file to client server
   unarchive:
      src: files/PerfProBenchmark.tar.gz
      dest: /root/
   delegate_to: "{{ item }}"
   with_items: "{{ groups['allserver'] }}"

 - name: copy config.yml file to client server
   copy:
     src: roles/perfPro/vars/config.yml
     dest: /root/PerfProBenchmark/
     owner: root
     group: root
     mode: '0644' 
   delegate_to: "{{ item }}"
   with_items: "{{ groups['allserver'] }}"
 
 - name: copy main.yml file to client server
   copy:
     src: roles/perfPro/vars/main.yml
     dest: /root/PerfProBenchmark/
     owner: root
     group: root
     mode: '0644'
   delegate_to: "{{ item }}"
   with_items: "{{ groups['allserver'] }}"

 - name: Create S3 account
   command: python3 /root/PerfProBenchmark/S3UserCreation/main_createusers.py /root/PerfProBenchmark/config.yml 
   delegate_to: "{{ groups['clientserver'][0] }}"

 - name: System monitoring started
   command: python3 /root/PerfProBenchmark/system_monitoring/systemMonitoring.py /root/PerfProBenchmark/main.yml 
   async: 21600
   poll: 0
   delegate_to: "{{ item }}"
   with_items: "{{ groups['allserver'] }}"

 - name: Configuration of s3bench benchmark tools  
   command: go get github.com/igneous-systems/s3bench
   delegate_to: "{{ groups['clientserver'][0] }}"

 - name: copying s3bench_meta binaries file to client server
   copy:
       src: files/s3bench_meta
       dest: /root/go/bin/
       owner: root
       group: root
       mode: '0754'
   delegate_to: "{{ groups['clientserver'][0] }}"

 - name: Make an entry for config.yml on a database
   command: python3 /root/PerfProBenchmark/addconfiguration.py '/root/PerfProBenchmark/main.yml' '/root/PerfProBenchmark/config.yml'
   delegate_to: "{{ groups['clientserver'][0] }}" 

 - name: S3benchmark running
   shell: cd /root/PerfProBenchmark/s3bench_meta; ./run_s3benchmark.sh -nc 50 -ns 2000 -s "1Kb";  ./run_s3benchmark.sh -nc 100 -ns 5000 -s "4Kb,100Kb,1Mb,5Mb";  ./run_s3benchmark.sh -nc 100 -ns 2000 -s "36Mb,64Mb,128Mb,256Mb"
   delegate_to: "{{ groups['clientserver'][0] }}"

 - name: Cosbench running
   shell: cd /root/PerfProBenchmark/cosbench; ./s3cosbench_benchmark.sh -nc "100" -ns "100" -s "1Mb,5Mb,36Mb,64Mb,128Mb,256Mb" -b 10,50 -w mixed -t 600; ./s3cosbench_benchmark.sh -nc "100" -ns "1000" -s "1Mb,5Mb,36Mb,64Mb,128Mb,256Mb" -b 1 -w mixed -t 600
   delegate_to: "{{ groups['clientserver'][0] }}"   

 - name: HSbench running
   shell: cd /root/PerfProBenchmark/hsbench; ./run_benchmark.sh -b 1 -o 1000 -s "4Kb,100Kb,1Mb,5Mb,36Mb,64Mb,128Mb,256Mb" -t 100 -d 600; ./run_benchmark.sh -b 10 -o 1000 -s "4Kb,100Kb,1Mb,5Mb,36Mb,64Mb,128Mb,256Mb" -t 100 -d 600; ./run_benchmark.sh -b 50 -o 5000 -s "4Kb,100Kb,1Mb,5Mb,36Mb,64Mb,128Mb,256Mb" -t 100 -d 600
   delegate_to: "{{ groups['clientserver'][0] }}"

 - name: Stop system monitoring
   command: python3 /root/PerfProBenchmark/system_monitoring/stopSystemMonitoring.py
   delegate_to: "{{ item }}"
   with_items: "{{ groups['allserver'] }}"

