---
 - name: Copying scsi rpm package
   copy:
       src: files/scsi-network-relay-1.1.0-47.x86_64.rpm
       dest: /root/
       owner: root
       group: root
       mode: '0754'
   delegate_to: "{{ item }}"
   with_items: "{{ groups['perfpros3server'] }}"

 - name: create /etc/scsi-network-relay.conf on "{{ groups['perfpros3server'][1] }}"
   copy:
       src: files/srvnode1
       dest: /etc/scsi-network-relay.conf
       owner: root
       group: root
       mode: '0754'
   delegate_to: "{{ groups['perfpros3server'][1] }}"

 - name: create /etc/scsi-network-relay.conf on "{{ groups['perfpros3server'][0] }}"
   copy:
       src: files/srvnode2
       dest: /etc/scsi-network-relay.conf
       owner: root
       group: root
       mode: '0754'
   delegate_to: "{{ groups['perfpros3server'][0] }}"

 - name: Installing scsi rpm packages
   yum: 
      name: /root/scsi-network-relay-1.1.0-47.x86_64.rpm
      state: present
   delegate_to: "{{ item }}"
   with_items: "{{ groups['perfpros3server'] }}"

 - name: start and enable scsi-network-relay service
   service:
       name: scsi-network-relay
       state: started
   delegate_to: "{{ item }}"
   with_items: "{{ groups['perfpros3server'] }}"

