#!/usr/bin/env bash
#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-


function patch_file() {
    cat $1 | while IFS="" read line; do

        if echo "$line" | grep "name" > /dev/null; then
            local section_name=$(echo "$line" | awk '{print $3}' | sed 's/"//g')
        fi

        if [[ -n "$S3_SERVER_MULTIPLICITY" && "$section_name" == "s3server" ]]; then
            echo "$line" | sed -r "s/multiplicity: [0-9]+/multiplicity: $S3_SERVER_MULTIPLICITY/"
        elif [[ -n "$MOTR_APP_MULTIPLICITY" && "$section_name" == "motr-app" ]]; then
            echo "$line" | sed -r "s/multiplicity: [0-9]+/multiplicity: $MOTR_APP_MULTIPLICITY/"
        else
            echo "$line"
        fi

    done
}

function parse_parameters() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -f|--file)
                MOTR_ROLE_MAPPINGS_FILE="$2"
                shift
                ;;
            -s|--s3server-multiplicity)
                S3_SERVER_MULTIPLICITY="$2"
                shift
                ;;
            -c|--motr-app-multiplicity)
                MOTR_APP_MULTIPLICITY="$2"
                shift
                ;;
            *)
                echo "unsupported parameter: $1"
                exit 1
                ;;
        esac
        shift
    done
}

function check_required_params() {
    if [[ -z "$MOTR_ROLE_MAPPINGS_FILE" ]]; then
        echo "invalid parameters"
        exit 1
    fi
}

parse_parameters "$@"
check_required_params
patch_file "$MOTR_ROLE_MAPPINGS_FILE"
