#!/usr/bin/env bash
#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-

function set_timeout()
{
    local user_defined_timeout=$1
    local time_val_fmt='[0-9]+'
    local time_unit_fmt='d|h|m|s'
    local fmt="^$time_val_fmt($time_unit_fmt)\$"

    if ! echo "$user_defined_timeout" | grep -P "$fmt"; then
        echo "invalid timeout format"
        exit 1
    fi

    local time_val=$(echo "$user_defined_timeout" | grep -P -o "$time_val_fmt")
    local time_unit=$(echo "$user_defined_timeout" | grep -P -o "$time_unit_fmt")

    local multiplier=''
    case $time_unit in
        d)
            multiplier=86400
            ;;
        h)
            multiplier=3600
            ;;
        m)
            multiplier=60
            ;;
        s)
            multiplier=1
            ;;
        *)
            echo "invalid time unit"
            exit 1
            ;;
    esac

    local time_val_sec=$(($time_val*$multiplier))
    local now=$(date '+%s')
    DEADLINE_UNIXTIME=$(($now+$time_val_sec))
}