---

 - name: PCS status before software update
   command: pcs status
   delegate_to: "{{ groups['perfpros3server'][1] }}"

 - name: Take a snap of cortx RPM packages before updates
   shell: "(rpm -qa|grep cortx) |tee before_update.txt"
   delegate_to: "{{ groups['perfpros3server'][1] }}"

 - name: Setting up update repo
   command: provisioner set_swupdate_repo --source "{{ BUILD_URL }}" "{{ RELEASE_TAG }}"
   delegate_to: "{{ groups['perfpros3server'][1] }}"

 - name: Verify the repo is set correctly
   command: salt-call pillar.get release:update:repos
   delegate_to: "{{ groups['perfpros3server'][1] }}"

 - name: Trigger software update
   command: provisioner sw_update 
   delegate_to: "{{ groups['perfpros3server'][1] }}"

 - name: Take a snap of cortx RPM packages after updates
   shell: "(rpm -qa|grep cortx) |tee after_update.txt"
   delegate_to: "{{ groups['perfpros3server'][1] }}"

 - name: PCS status after software update
   command: pcs status
   delegate_to: "{{ groups['perfpros3server'][1] }}"

 - name: Differentiate rpm packages before and after updates
   shell: "cd /root/; diff before_update.txt after_update.txt"
   delegate_to: "{{ groups['perfpros3server'][1] }}"

