#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-


figures:
# CPU
- figure:
    fname: "[HOSTNAME]__cpu.png"
    name: "[HOSTNAME] CPU stats"
    columns:
    - column:
      - graph:
          title: CPU utilisation
          display_as: percent
          y_label: 'CPU Time [%]'
          metrics:
          - cpu_total
          - cpu_user
          - cpu_system
      - graph:
          title: CPU iowait
          display_as: percent
          y_label: 'CPU Time [%]'
          metrics:
          - cpu_iowait
      - graph:
          title: CPU context switches
          y_label: 'switches per second'
          metrics:
          - cpu_ctx_switches
# Interrupts
- figure:
    fname: "[HOSTNAME]__interrupts.png"
    name: "[HOSTNAME] CPU interrupts"
    columns:
    - column:
      - graph:
          title: CPU interrupts
          y_label: 'interrupts per second'
          metrics:
          - cpu_interrupts
          - cpu_soft_interrupts
      - graph:
          title: handling interrupts
          display_as: percent
          y_label: 'CPU Time [%]'
          metrics:
          - cpu_irq
          - cpu_softirq
# CPU cores
- figure:
    USE_AS_TEMPLATE_FOR: CPU_NR
    fname: "[HOSTNAME]__percpu__[TEMPLATE].png"
    name: CPU [TEMPLATE] stats
    columns:
    - column:
      - graph:
          title: CPU [TEMPLATE] utilisation
          display_as: percent
          y_label: 'CPU Time [%]'
          metrics:
          - percpu_[TEMPLATE]_total
          - percpu_[TEMPLATE]_user
          - percpu_[TEMPLATE]_system
# PERCPU summary
- figure:
    fname: "[HOSTNAME]__percpusum.png"
    name: CPU stats
    columns:
    - column:
      - graph:
          title: CPUs total utilisation
          display_as: percent
          show_legend: false
          y_label: 'CPU Time [%]'
          metrics:
          - percpu_[CPU_NR]_total
      - graph:
          title: CPUs user utilisation
          display_as: percent
          show_legend: false
          y_label: 'CPU Time [%]'
          metrics:
          - percpu_[CPU_NR]_user
      - graph:
          title: CPUs system utilisation
          display_as: percent
          show_legend: false
          y_label: 'CPU Time [%]'
          metrics:
          - percpu_[CPU_NR]_system
# Memory
- figure:
    fname: "[HOSTNAME]__mem.png"
    name: "[HOSTNAME] memory stats"
    columns:
    - column:
      - graph:
          title: Memory usage
          display_as: GB
          y_label: 'GB'
          metrics:
          - mem_total
          - mem_available
          - mem_used
          - mem_free
          - mem_active
      - graph:
          title: Swap usage
          display_as: GB
          y_label: 'GB'
          metrics:
          - memswap_total
          - memswap_used
          - memswap_free
# CPU and memory
- figure:
    fname: "[HOSTNAME]__cpumem.png"
    name: "[HOSTNAME] CPU/Memory usage"
    columns:
    - column:
      - graph:
          title: CPU/Memory/Swap
          display_as: percent
          y_label: 'usage [%]'
          metrics:
          - cpu_total
          - mem_percent
          - memswap_percent
# Data volumes summary
# - figure:
#     fname: "[HOSTNAME]__datavolumesummary.png"
#     name: data volume stats
#     columns:
#     - column:
#       - graph:
#           title: diskio requests (write)
#           show_legend: false
#           y_label: "RpS"
#           metrics:
#           - diskio_[DATA_VOLUMES]_write_count
#       - graph:
#           title: diskio requests (read)
#           show_legend: false
#           y_label: "RpS"
#           metrics:
#           - diskio_[DATA_VOLUMES]_read_count
#       - graph:
#           title: diskio (write)
#           show_legend: false
#           display_as: MB
#           y_label: "MB/s"
#           metrics:
#           - diskio_[DATA_VOLUMES]_write_bytes
#       - graph:
#           title: diskio (read)
#           show_legend: false
#           display_as: MB
#           y_label: "MB/s"
#           metrics:
#           - diskio_[DATA_VOLUMES]_read_bytes
# Data volumes
# - figure:
#     USE_AS_TEMPLATE_FOR: DATA_VOLUMES
#     fname: "[HOSTNAME]__datavolume__[TEMPLATE].png"
#     name: data volume [TEMPLATE] stats
#     columns:
#     - column:
#       - graph:
#           title: diskio requests [TEMPLATE]
#           y_label: "RpS"
#           metrics:
#           - diskio_[TEMPLATE]_write_count
#           - diskio_[TEMPLATE]_read_count
#       - graph:
#           title: diskio [TEMPLATE]
#           display_as: MB
#           y_label: "MB/s"
#           metrics:
#           - diskio_[TEMPLATE]_write_bytes
#           - diskio_[TEMPLATE]_read_bytes
# MD volumes
# - figure:
#     USE_AS_TEMPLATE_FOR: METADATA_VOLUMES
#     fname: "[HOSTNAME]__mdvolume__[TEMPLATE].png"
#     name: metadata volume [TEMPLATE] stats
#     columns:
#     - column:
#       - graph:
#           title: diskio requests [TEMPLATE]
#           y_label: "RpS"
#           metrics:
#           - diskio_[TEMPLATE]_write_count
#           - diskio_[TEMPLATE]_read_count
#       - graph:
#           title: diskio [TEMPLATE]
#           display_as: MB
#           y_label: "MB/s"
#           metrics:
#           - diskio_[TEMPLATE]_write_bytes
#           - diskio_[TEMPLATE]_read_bytes

# Network
- figure:
    USE_AS_TEMPLATE_FOR: NETWORK_IFACES
    fname: "[HOSTNAME]__net__[TEMPLATE].png"
    name: network interface stats [TEMPLATE]
    columns:
    - column:
      - graph:
          title: net iface bit rate [TEMPLATE]
          display_as: MB
          y_label: "bit rate [MB/s]"
          metrics:
          - network_[TEMPLATE]_rx
          - network_[TEMPLATE]_tx
      - graph:
          title: net iface stats [TEMPLATE]
          display_as: MB
          y_label: "total traffic [MB]"
          metrics:
          - network_[TEMPLATE]_cumulative_rx
          - network_[TEMPLATE]_cumulative_tx
