---
 - name: "[local-pre-req] : Required packages on localhost"
   yum:
      name: expect
      state: present

 - name: "[local-pre-req] : Generate SSH key 'id_rsa' on localhost"
   openssh_keypair:
      path: "~/.ssh/id_rsa_perfline"
      type: rsa
      size: 4096
      state: present
      force: no
 
 - name: "[local-pre-req] : Enabling Passwordless SSH from perfline master server"
   script: files/passwordless_ssh.sh {{ hostvars[item]['ansible_user'] }} {{ hostvars[item]['ansible_host'] }} {{ CLUSTER_PASS }}
   ignore_errors: true
   with_items: "{{ groups['all'] }}"

 - name: "[server-pre-req] : Required packages on all servers"
   yum:
      name: expect
      state: present
   delegate_to: "{{ item }}"
   with_items: "{{ groups['all'] }}"

 - name: "[cluster-pre-req] : Generate SSH key 'id_rsa' to all servers"
   openssh_keypair:
      path: "~/.ssh/id_rsa_perfline"
      type: rsa
      size: 4096
      state: present
      force: no
   delegate_to: "{{ item }}"
   with_items: "{{ groups['all'] }}"

 - name: "[client-pre-req] : Enabling Passwordless SSH from cortx client server"
   script: files/passwordless_ssh.sh {{ hostvars[item]['ansible_user'] }} {{ hostvars[item]['ansible_host'] }} {{ CLUSTER_PASS }}
   ignore_errors: true
   delegate_to: "client-1"
   with_items: "{{ groups['all'] }}"

 - name: "[servers-pre-req] : Enabling Passwordless SSH from cortx servers to cortx-client"
   script: files/passwordless_ssh.sh {{ hostvars[item]['ansible_user'] }} {{ hostvars['client-1']['ansible_host'] }} {{ CLUSTER_PASS }}
   ignore_errors: true
   delegate_to: "{{ item }}"
   with_items: "{{ groups['nodes'] }}"

 - name: "[client-pre-req] : Adding Identityfile on /etc/ssh/ssh_config file"
   lineinfile: 
      path: "/etc/ssh/ssh_config"
      line: "   IdentityFile ~/.ssh/id_rsa_perfline"
   delegate_to: "{{ item }}"
   with_items: "{{ groups['all'] }}"

 - name: "[client-pre-req] : Restart sshd service"
   systemd: state=restarted name=sshd
   delegate_to: "{{ item }}"
   with_items: "{{ groups['all'] }}"
