---
# tasks file for perfline_setup
  - name: Creating perfline directory
    file:
      path: /var/perfline
      state: directory
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: Copy perfline working dir
    copy:
      src: files/wrapper
      dest: "{{ perfline_dir }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: Changing permission for execution for perfline scripts
    file: path=/root/perfline/wrapper/scripts mode=a+x state=directory recurse=yes
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: Changing permission for execution for stat scripts
    file: path=/root/perfline/wrapper/stat mode=a+x state=directory recurse=yes
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: Changing permission for execution for stat scripts
    file: path=/root/perfline/wrapper/workload mode=a+x state=directory recurse=yes
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: Changing permission for execution for perfline.py
    file: dest=/root/perfline/wrapper/perfline.py mode=a+x
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - include: taskq.yml
