---
  - name: "Creating artifacts directory /var/perfline"
    file:
      path: /var/perfline
      state: directory
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: "Creating perfline directory {{ perfline_dir }}"
    file:
      path: "{{ perfline_dir }}/bin"
      state: directory
      recurse: yes
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: "Compress directory files/wrapper into files/wrapper.tar.gz"
    archive:
      path: "{{ role_path }}/files/wrapper"
      dest: "{{ role_path }}/files/wrapper.tar.gz"

  - name: "Copy perfline wrapper scripts"
    unarchive:
      src: "{{ role_path }}/files/wrapper.tar.gz"
      dest: "{{ perfline_dir }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"


  - name: "Create List of nodes to be added into Cluster"
    set_fact: nodelist={%for host in groups['nodes']%}{{hostvars[host]['ansible_host']}}{% if not loop.last %},{% endif %}{% endfor %}

  - name: "Updating value of a variables in perfline.conf"
    lineinfile:
       path: "{{ role_path }}/files/perfline.conf"
       regexp: "^{{ item.variable }}"
       line: "{{ item.variable }}='{{ item.value }}'"
    with_items:
       - { variable: 'HA_TYPE', value: '{{ ha_type }}'}
       - { variable: 'NODES', value: '{{ nodelist }}' }
       - { variable: 'PERFLINE_DIR', value: '{{ perfline_dir }}'}
       - { variable: 'WORKLOAD_DIR', value: '{{ perfline_dir }}/wrapper/workload'}
       - { variable: 'VALIDATOR', value: '{{ perfline_dir }}/wrapper/core'}
       - { variable: 'PL_SCRIPT_PATH', value: '{{ perfline_dir }}/wrapper/perfline.py'}

  - name: "Installing golang version above 1.15 on localhost"
    yum:
      name: go >= 1.15
      state: present

  - name: "Generating S3bench binary files"
    shell: GO111MODULE=on go get github.com/Seagate/s3bench@{{ S3BENCH_COMMIT_ID }}

  - name: "Copy new s3bench binary file to client machine"
    copy:
       src: "/root/go/bin/s3bench"
       dest: "{{ perfline_dir }}/bin/s3bench_perfline"
       mode: '0751'
    delegate_to: "client-1"

