---
  - name: Compress directory files/webui into files/webui.tar.gz
    archive:
      path: "{{ role_path }}/files/webui"
      dest: "{{ role_path }}/files/webui.tar.gz"
   

  - name: Copy perfline webui scripts
    unarchive:
      src: "{{ role_path }}/files/webui.tar.gz"
      dest: "{{ perfline_dir }}"
    delegate_to: "client-1"

  - name: Compress directory files/chronometry into files/chronometry.tar.gz
    archive:
      path: "{{ role_path }}/files/chronometry"
      dest: "{{ role_path }}/files/chronometry.tar.gz"
   
  - name: Copy perfline chronometry scripts
    unarchive:
      src: "{{ role_path }}/files/chronometry.tar.gz"
      dest: "{{ perfline_dir }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"
 
  - name: Compress directory files/chronometry_v2 into files/chronometry_v2.tar.gz
    archive:
      path: "{{ role_path }}/files/chronometry_v2"
      dest: "{{ role_path }}/files/chronometry_v2.tar.gz"

  - name: Copy perfline chronometry_v2 scripts
    unarchive:
      src: "{{ role_path }}/files/chronometry_v2.tar.gz"
      dest: "{{ perfline_dir }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  
  - name: Copy perfline.conf file
    copy:
      src: files/perfline.conf
      dest: "{{ perfline_dir }}"
    delegate_to: "client-1"

#  - name: Open port for webui
#    firewalld: port=8005/tcp zone=public permanent=true state=enabled immediate=yes


  - name: Install perfline python dependencies
    pip:
      name:
        - huey >= 2.3.0
        - plumbum
        - cerberus
        - pandas
        - matplotlib
        - Flask
        - PyYAML
        - Jinja2
        - tqdm
        - iostat-tool
        - peewee
        - graphviz
      executable: pip3
      extra_args: -i https://pypi.org/simple
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: Install perfline system dependencies
    yum:
      name:
        - ansible
        - sysstat
        - pdsh
        - dstat
        - blktrace
        - iowatcher
        - python3-devel
        - ftp
        - fio
        - iperf
      state: present
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"


  - name: "Coping a block of statement in perfline.service file"
    blockinfile:
      path: /etc/systemd/system/perfline-ui.service
      create: yes
      block: |
                [Unit]
                Description=web ui for perfline
                
                [Service]
                Type=simple
                WorkingDirectory={{ perfline_dir }}/webui
                ExecStart=/usr/bin/python3.6 {{ perfline_dir }}/webui/server.py
                
                [Install]
                WantedBy=multi-user.target
    delegate_to: "client-1" 

  - name: "Coping a block of statement in perfline-ui.service file"
    blockinfile:
      path: /etc/systemd/system/perfline.service
      create: yes
      block: |
                [Unit]
                Description=Perfline service
                
                [Service]
                Type=simple
                Restart=always
                WorkingDirectory={{ perfline_dir }}/wrapper
                ExecStart=/usr/bin/bash {{ perfline_dir }}/wrapper/run_pl
                
                [Install]
                WantedBy=multi-user.target
    delegate_to: "client-1"

  - name: Start perfline-ui service
    systemd: state=restarted name=perfline-ui daemon_reload=yes
    delegate_to: "client-1"

  - name: Start perfline service
    systemd: state=restarted name=perfline daemon_reload=yes
    delegate_to: "client-1"
