---
  - name: Copy webui dir
    copy:
      src: files/webui
      dest: "{{ perfline_dir }}"
    delegate_to: "client-1"

  - name: Copy chronometry dir
    copy:
      src: files/chronometry
      dest: "{{ perfline_dir }}"
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"


#  - name: Open port for webui
#    firewalld: port=8005/tcp zone=public permanent=true state=enabled immediate=yes

  - name: Install perfline python dependencies
    pip:
      name:
        - huey
        - plumbum
        - cerberus
        - pandas
        - matplotlib
        - Flask
        - PyYAML
        - Jinja2
        - tqdm
        - iostat-tool
        - peewee
      executable: pip3
      extra_args: -i https://pypi.org/simple
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: Install perfline system dependencies
    yum:
      name:
        - sysstat
        - pdsh
        - dstat
        - blktrace
        - iowatcher
      state: present
    delegate_to: "{{ item }}"
    with_items: "{{ groups['all'] }}"

  - name: Copy webui systemd file
    copy:
      src: files/webui.service
      dest: /etc/systemd/system/webui.service
    delegate_to: "client-1"

  - name: Copy huey-consumer systemd file
    copy:
      src: files/huey-consumer.service
      dest: /etc/systemd/system/huey-consumer.service
    delegate_to: "client-1"

  - name: Start webui service
    systemd: state=started name=webui daemon_reload=yes
    delegate_to: "client-1"

  - name: Start huey-consumer service
    systemd: state=started name=huey-consumer daemon_reload=yes
    delegate_to: "client-1"
