#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-

common:
  version: 1
  description: Perf benchmark example
  priority: 1
  batch_id: null
  user: user@seagate.com
  send_email: false

custom_build:
  motr:
    repo: "https://github.com/Seagate/cortx-motr.git"
    branch: b64b1bba
  s3server:
    repo: "https://github.com/Seagate/cortx-s3server.git"
    branch: c482a593
  hare:
    repo: "https://github.com/Seagate/cortx-hare.git"
    branch: daddc4a

# Optional section. It may be deleted in case you don't want
# to customize Cortx components configuration.
configuration:
  hare:
    custom_cdf: /root/path/to/cdf/file.yaml
    data_units: 4
    parity_units: 2
    spare_units: 2
  motr:
    custom_file: /root/path/to/motr/file.yaml
    config_overrides:
      MOTR_MOD_ADDB_RECORD_SIZE: 1073741824
  s3:
    custom_file: /root/path/to/s3conf/file.yaml
    instances_per_node: 23
    config_overrides:
      S3_BUCKET_METADATA_CACHE_MAX_SIZE: 10000
      S3_BUCKET_METADATA_CACHE_EXPIRE_SEC: 5
      S3_BUCKET_METADATA_CACHE_REFRESH_SEC: 4
  s3bg_delete:
    custom_file: /root/path/to/s3bgdelete/file.yaml
    config_overrides:
      scheduler_schedule_interval: 1200
  haproxy:
    custom_file: /root/path/to/haproxy/file.yaml
    execution_type: nbthread
    parallel_instances: 16
    total_maxconn: 200
    maxconn_per_instance: 50
  lnet:
    custom_file: /root/path/to/lnet/file.yaml
  ko2iblnd:
    custom_file: /root/path/to/ko2iblnd/file.yaml

stats_collection:
  iostat: false
  dstat: false
  blktrace: false
  glances: false

# List of benchmarks and parameters. This section must include
# at least one benchmark (custom/fio/s3bench/m0crate).
benchmarks:
  - custom:
      cmd: sleep 1
  - lnet:
      LNET_OPS: read,write,ping              # user can pass value operation separated by ',' Ex: read,write,ping
  - fio:
      Duration: 600
      BlockSize: 8M
      NumJobs: 32
      Template: seq_read_fio       #Template for fio like seq_read_fio, seq_write_fio, randmix_80-20_fio, randmix_20-80_fio and rand_fio
  - iperf:
      Interval: 1
      Duration: 60
      Parallel: 2

workloads:
  - s3bench:
      BucketName: mybucket
      NumClients: 10
      NumSample: 100
      ObjSize: 32Mb
      EndPoint: https://s3.seagate.com
  - m0crate:
      NR_INSTANCES_PER_NODE: 2
      NR_THREADS: 2
      BLOCK_SIZE: 2m
      IOSIZE: 4m


execution_options:
  mkfs: false
  collect_m0trace: false
  collect_addb: false
  backup_result: false
