#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-

common:
  version: 1
  description: s3bench workloads. Object size 4Mb. Clients 100-900
  priority: 1
  batch_id: null
  user: user@seagate.com
  send_email: false


stats_collection:
  iostat: true
  dstat: true
  blktrace: true
  glances: true

workloads:
  - s3bench:
      BucketName: mybucket
      NumClients: 100
      NumSample: 40000
      ObjSize: 4Mb
      EndPoint: http://s3.seagate.com
  - s3bench:
      BucketName: mybucket
      NumClients: 200
      NumSample: 40000
      ObjSize: 4Mb
      EndPoint: http://s3.seagate.com
  - s3bench:
      BucketName: mybucket
      NumClients: 300
      NumSample: 40000
      ObjSize: 4Mb
      EndPoint: http://s3.seagate.com
  - s3bench:
      BucketName: mybucket
      NumClients: 400
      NumSample: 40000
      ObjSize: 4Mb
      EndPoint: http://s3.seagate.com
  - s3bench:
      BucketName: mybucket
      NumClients: 500
      NumSample: 40000
      ObjSize: 4Mb
      EndPoint: http://s3.seagate.com
  - s3bench:
      BucketName: mybucket
      NumClients: 600
      NumSample: 40000
      ObjSize: 4Mb
      EndPoint: http://s3.seagate.com
  - s3bench:
      BucketName: mybucket
      NumClients: 700
      NumSample: 40000
      ObjSize: 4Mb
      EndPoint: http://s3.seagate.com
  - s3bench:
      BucketName: mybucket
      NumClients: 800
      NumSample: 40000
      ObjSize: 4Mb
      EndPoint: http://s3.seagate.com
  - s3bench:
      BucketName: mybucket
      NumClients: 900
      NumSample: 40000
      ObjSize: 4Mb
      EndPoint: http://s3.seagate.com

execution_options:
  mkfs: true
  collect_m0trace: true
  collect_addb: false
  backup_result: false

