#!/usr/bin/env bash
#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-
#

set -e
#set -x

SCRIPT_PATH="$(readlink -f $0)"
SCRIPT_DIR="${SCRIPT_PATH%/*}"

. ${SCRIPT_DIR}/common/remote_execution

SRV_CLI_MAP=$1
WORKLOAD=$2

trap set_term_flag SIGTERM

function main()
{
    parse_nodes
    check_required_parameters

    local iter=0

    while [[ -z $TERMINATE_FLAG ]]; do
        sleep 20
        echo -e "============== start iteration $iter ($(date)) ================\n"
        set +e
        $EX_SRV $SCRIPT_DIR/s3server_integration/s3cli_s3bench \"$SRV_CLI_MAP\" \"$WORKLOAD\"
        set -e
        echo -e "============== end iteration $iter ($(date)) ================\n\n"
        iter=$((iter+1))
    done
}

function set_term_flag()
{
    echo "got termination request"
    TERMINATE_FLAG=1
}

function check_required_parameters()
{
    if [[ -z $SRV_CLI_MAP || -z $WORKLOAD ]]; then
        echo "missed required parameter"
        echo "Usage: ./endless_s3bench $SRV_CLI_MAP $workload"
        exit 1
    fi
}

main
exit $?
