#!/usr/bin/env bash
#
#
# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#
# -*- coding: utf-8 -*-
#

set -x
set -e

FIO_TESTS_DIR=$1
FIO_RESULTS_DIR="/tmp/fio_results"

function run_fio_tests() {
    mkdir -p $FIO_RESULTS_DIR
    rm -f $FIO_RESULTS_DIR/*

    for fio_test in $(ls "$FIO_TESTS_DIR" | grep $(hostname -s)); do
        fio "$FIO_TESTS_DIR"/"$fio_test" > $FIO_RESULTS_DIR/"${fio_test}".txt
    done
}

run_fio_tests
